node = {
    "RTK":[
        "EGFR",
        "ERBB2",
        "ERBB4",
        "FGFR1",
        "FGFR2",
        "FGFR3",
        "KIT",
        "NF1",
        "PDGFRA",
        "KRAS",
        "HRAS",
        "NRAS",
        "BRAF",
        "RAF1"],
    "Nrf2":[
        "KEAP1",
        "NFE2L2"
    ],
    "PI3K":[
        "PTEN",
        "PIK3CA",
        "PIK3R1",
        "AKT1",
        "PPP2R1A",
        "MTOR",
        "STK11",
        "RICTOR"
    ],
    "P53":[
        "ATM",
        "TP53",
        "MDM4",
        "CDKN2A",
        "CDKN2B",
        "CCND1",
        "CDK4",
        "CDKN1A",
        "CCNE1",
        "RB1",
        "E2F3"
    ],
    "TGF":[
        "TGFBR2",
        "ACVR2A",
        "SMAD4"
    ],
    "Myc":[
        "MGA"
    ],
    "Wnt":[
        "DKK4",
        "RNF43",
        "APC",
        "CTNNB1",
        "TCF7L2"
    ],
    "Hippo":[
        "DCHS2",
        "FAT1",
        "TAOK2",
        "NF2"
    ],
    "Notch":[
        "FBXW7",
        "NOTCH1",
        "CREBBP",
        "EP300"
    ]
}